services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 3000:8080
    environment:
      - DOTNET_ENVIRONMENT=Docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3001:80
    environment:
      - DOTNET_ENVIRONMENT=Docker
    depends_on:
      - api
    networks:
      - app_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:

volumes:
  postgres_data:
